services:
    _defaults:
        public: true
    emp.form.type.description:
        class: 'Ets\MarketPlace\FormType\DescType'
        decorates: 'form.type.sell.product.description.description_type'
        parent: 'form.type.translatable.aware'
        public: true
        arguments:
            - '@router'
            - '@=service("prestashop.adapter.legacy.context").getEmployeeLanguageIso()'
            - '@=service("prestashop.adapter.legacy.configuration").get("PS_PRODUCT_SHORT_DESC_LIMIT")'
        tags:
            - { name: form.type }